language: csharp
mono: none
dotnet: 2.2.103
solution: NetCasbin.sln

matrix:
  include:
    - os: linux
      # .NET Core 2.2 requires Ubuntu 16.04+ (Xenial)
      # https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md#linux
      # The default vesion in Travis CI is currently 14.04 (Trusty)
      dist: xenial
    - os: osx
      # .NET Core 2.2 requires OSX 10.12+
      # https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md#macos
      # The default version in Travis CI is currently OS X 10.13 so nothing needs to be done
      # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version

branches:
  only:
  - master
  # We'll also build whenever there is a new commit on any branch starting with `features/`
  - /features\/.+/

script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet tool install -g Cake.Tool --version 0.31.0
  - dotnet cake build.cake --bootstrap
  - dotnet cake build.cake --pack
